In [1]:
import PyRadioTrace.models as models
from PyRadioTrace.models import GeoModel
from PyRadioTrace.jones_stephenson import Raytracer
import datetime as dt 
import numpy as np 
import matplotlib.pyplot as plt
import scipy.constants as const

# Models

In [2]:
test_lat = 40 # degrees
test_lon = -110 # degrees
test_alt = 40e3 # meters

neutral = models.ScaleHeight(N0 = 400, H = 7e3)
magneto = models.IGRF(dt.datetime(2023, 1, 1))
iono = models.EpsteinLayersModel()

All neutral atmosphere models should return the index of refraction as well the spherical spatial derivatives.

In [3]:
neutral(test_lat, test_lon, test_alt)

(np.float64(1.0000013194023023),
 array([-1.88486043e-10,  0.00000000e+00,  0.00000000e+00]))

All ionosphere models should return the electron density as well the spherical spatial derivatives.

In [4]:
iono(test_lat, test_lon, test_alt)

(np.float64(21935836.509093076),
 array([935.39927486,   0.        ,   0.        ]))

The IGRF object returns the magnetic field, magnetic jacobian, and magnetic field strength spherical derivatives. 

In [5]:
magneto(test_lat, test_lon, test_alt)

(array([[-3.57350256e+98],
        [ 8.91385642e+97],
        [-9.57329235e+97]]),
 array([[[ 3.57350256e+95],
         [-2.16218843e+97],
         [-2.18299095e+96]],
 
        [[-8.91385642e+94],
         [-1.29969497e+98],
         [-8.10884744e+96]],
 
        [[ 9.57329235e+94],
         [ 1.04755516e+98],
         [-3.01328857e+96]]]),
 array([[3.80538673e+95],
        [1.68324966e+98],
        [8.92181396e+96]]))

# Raytracing 

Instantiate a Raytracer object with the models above 

In [6]:
Raytrace  = Raytracer(iono = iono, magneto = None, neutral = neutral)

In [7]:
rtol = 1e-10
atol = 1e-8
transmit_lat = 0
transmit_lon = 7.5
transmit_alt = 800e3
f = 1575.42e6

az = 90
el = -10

In [ ]:
distances_to_evaluate = np.arange(0, 100e3, 1)

In [ ]:
ray_solution = Raytrace.ray_propagate(transmit_lat,
                                    transmit_lon, 
                                    transmit_alt,
                                    az,
                                    el,
                                    f, 
                                    group_path_distances = distances_to_evaluate,
                                    rtol = rtol,
                                    atol = atol)
ray_solution